export const siteConfig = {
  name: "solidweb",
  description: "생각을 응원하는 곳, 우리와 함께합니다.",
  hero: {
    title: "보여주는 웹이 아니라, 결과를 만드는 웹을.",
    subtitleMain: "전략 기획부터 전환 설계, 성과 측정까지 한 번에.",
    subtitleEnd: "디자인을 넘어 비즈니스 성과로 직결되는 웹을 제작하고, 방문을 고객으로 노출을 매출로 이어드는 구조를 설계합니다.",
    support: "",
    ctaText: "무료 상담 신청하기",
  },
  nav: {
    consult: "상담 신청",
    items: [
      { label: "솔리드웹", href: "/" },
      { label: "포트폴리오", href: "/portfolio" },
      { label: "문의하기", href: "/contact" },
    ],
  },
  whatWeDo: {
    title: "01 What We Do",
    subtitle: "우리는 다양한 분야에서 차별화된 비즈니스를 제공합니다.",
    items: [
      {
        number: 1,
        title: "서비스 기획",
        description: "체계적인 기획부터 완성도 높은 설계까지 차별화된 서비스 경험을 제공합니다.",
        list: ["서비스 기획 및 설계", "디자인 및 개발", "운영 및 유지보수"],
      },
      {
        number: 2,
        title: "웹/앱 개발",
        description: "전문적인 개발 기술력으로 사용자에게 최적화된 웹/앱 서비스를 제공합니다.",
        list: ["프론트엔드 개발", "백엔드 개발", "모바일 앱 개발"],
      },
      {
        number: 3,
        title: "브랜딩",
        description: "고객사의 브랜드를 이해하고 차별화된 브랜드 가치를 구축합니다.",
        list: ["브랜드 전략 수립", "BI/CI 디자인", "마케팅 컨설팅"],
      },
    ],
  },
  ourStrength: {
    title: "02 Our Strength",
    subtitle: "차별화된 경쟁력으로 고객사의 성공을 지원합니다.",
    items: [
      {
        icon: "shield" as const,
        title: "전문성",
        description: "다양한 분야의 전문가들이 모여 최적의 솔루션을 제공합니다.",
      },
      {
        icon: "lightbulb" as const,
        title: "혁신성",
        description: "최신 기술 트렌드를 반영하여 혁신적인 서비스를 제공합니다.",
      },
      {
        icon: "heart" as const,
        title: "고객 중심",
        description: "고객의 니즈를 최우선으로 생각하며, 최상의 만족도를 제공합니다.",
      },
      {
        icon: "trending-up" as const,
        title: "지속적인 성장",
        description: "고객사와 함께 성장하며, 지속적인 발전을 추구합니다.",
      },
    ],
  },
  projects: {
    title: "Our Projects",
    sectionLabel: "03",
    descriptionLines: [
      "우리가 함께 만든 프로젝트들은",
      "사용성과 기술, 그리고 디자인의 조화를 추구합니다.",
    ],
    subtitle: "우리의 성공적인 프로젝트들을 만나보세요.",
    viewMoreLabel: "프로젝트 더보기",
    featured: {
      title: "ISAC Food",
      description: "ISAC Food는 (주)이삭푸드의 새로운 브랜드 아이덴티티 구축 및 웹사이트 개발 프로젝트입니다.",
    },
    items: [
      { title: "Project A", desc: "웹/앱 개발" },
      { title: "Project B", desc: "브랜딩" },
      { title: "Project C", desc: "마케팅" },
      { title: "Project D", desc: "솔루션" },
      { title: "Project E", desc: "웹/앱" },
      { title: "Project F", desc: "브랜딩" },
    ],
  },
  portfolioPage: {
    heading: "What We Do",
    description: "솔리드웹은 단순히 기능을 구현하는 데 그치지 않습니다. 사용자 경험을 중심에 두고, 클라이언트의 목표와 사용자의 니즈가 자연스럽게 연결되도록 설계합니다.",
    projectButtonLabel: "상세 보기",
    projects: [
      { title: "알체라 AI", description: "", image: "/portfolio/alchera.webp", link: "http://alcherainc.com/" },
      { title: "LG 유니참", description: "", image: "/portfolio/lgucpet.webp", link: "https://lgucpet.co.kr/" },
      { title: "백상예술대상", description: "", image: "/portfolio/baeksang.webp", link: "https://www.baeksangawards.co.kr/" },
      { title: "소망교회", description: "", image: "/portfolio/somang.webp", link: "https://somang.net/home" },
      { title: "콜렉트", description: "Web development, Web design", image: "/portfolio/collect.webp", link: "https://www.collectluxe.com/" },
      { title: "cafe mememi", description: "", image: "/portfolio/mememi.webp", link: "https://www.cafemememi.com/" },
      { title: "와이즈 웨딩", description: "Web development, Web design", image: "/portfolio/wisewedding.webp", link: "http://www.wisewedding.co.kr/" },
      { title: "mostapes", description: "", image: "/portfolio/mostapes.webp", link: "http://mostapes.com/" },
      { title: "NHN KCP", description: "", image: "/portfolio/kcp.webp", link: "https://www.kcp.co.kr/" },
      { title: "NHN 클라우드", description: "", image: "/portfolio/nhncloud.webp", link: "https://company.nhncloud.com/" },
      { title: "nots korea", description: "", image: "/portfolio/notskorea.webp", link: "http://notskorea.com/index.nots" },
      { title: "기아 인재채용", description: "", image: "/portfolio/kia.webp", link: "https://career.kia.com/main/main.kc" },
      { title: "아스티 캐빈", description: "", image: "/portfolio/astycabin.webp", link: "https://www.astycabin.co.kr/" },
      { title: "국제특허이창", description: "", image: "/portfolio/echangpat.webp", link: "https://echangpat.com/" },
      { title: "데브시스터즈", description: "", image: "/portfolio/devsisters.webp", link: "https://www.devsisters.com/" },
      { title: "동국제약", description: "", image: "/portfolio/dkbrand.webp", link: "https://dkbrand.co.kr/" },
      { title: "깨끗한 나라", description: "", image: "/portfolio/kleannara.webp", link: "https://www.kleannara.co.kr/Main/main" },
      { title: "생명보험협회", description: "", image: "/portfolio/klia.webp", link: "https://www.klia.or.kr/" },
      { title: "LG 마미포코", description: "", image: "/portfolio/mamypoko.webp", link: "https://mamypoko.co.kr/" },
      { title: "허스트 중앙", description: "", image: "/portfolio/hjmembers.webp", link: "https://www.hjmembers.co.kr/" },
      { title: "에스쁘아", description: "", image: "/portfolio/espoir.webp", link: "https://www.espoir.com/ko/main.do" },
      { title: "MUA", description: "", image: "/portfolio/muameditation.webp", link: "https://muameditation.com/ko/main.do" },
      { title: "국립태권도박물관", description: "", image: "/portfolio/larchiveum.webp", link: "https://larchiveum.tpf.or.kr/" },
      { title: "코나아이", description: "", image: "/portfolio/konai.webp", link: "https://konai.com/" },
      { title: "테라에너지", description: "", image: "/portfolio/teraenergy.webp", link: "http://www.teraenergy.co.kr/" },
      { title: "렉서스코리아", description: "", image: "/portfolio/lexus.webp", link: "https://www.lexus.co.kr/" },
      { title: "웰컴에프엔디", description: "", image: "/portfolio/welcomefnd.webp", link: "https://www.welcomefnd.com/" },
      { title: "대한민국은 공연중", description: "", image: "/portfolio/kstagefesta.webp", link: "https://kstagefesta.kr/" },
      { title: "에이투지라운지", description: "", image: "/portfolio/atozlounge.webp", link: "https://atozlounge.com/" },
      { title: "포스코DX", description: "", image: "/portfolio/poscodx.webp", link: "https://www.poscodx.com/kor/" },
      { title: "레카 벤처스", description: "", image: "/portfolio/leccaventures.webp", link: "https://leccaventures.com/" },
      { title: "주님의교회 유아숲", description: "", image: "/portfolio/pclkids.webp", link: "https://pclkids.co.kr/" },
      { title: "motion air compressors", description: "", image: "/portfolio/motionaircompressors.webp", link: "https://motionaircompressors.com/" },
      { title: "명지반도체", description: "", image: "/portfolio/myungjisemi.webp", link: "https://myungjisemi.com/" },
      { title: "경희대학교 실감미디어 사업단", description: "", image: "/portfolio/imcoss.webp", link: "https://imcoss.khu.ac.kr/" },
      { title: "소다미술관", description: "", image: "/portfolio/museumsoda.webp", link: "https://museumsoda.org/" },
      { title: "NK MEDICS", description: "", image: "/portfolio/nkmedics.webp", link: "https://nkmedics.co.kr/" },
      { title: "디자인코리아", description: "", image: "/portfolio/designkorea.webp", link: "https://designkorea.kidp.or.kr/" },
      { title: "네이버 AI RUSH", description: "", image: "/portfolio/airush.webp", link: "https://airush.ncloud.com/" },
      { title: "소망교회 추모사이트", description: "", image: "/portfolio/lettersomang.webp", link: "https://lettersomang.net/" },
    ],
  },
  review: {
    title: "04 Review",
    subtitle: "고객들의 솔직한 후기를 들어보세요.",
    items: [
      { author: "권**", subtitle: "", quote: "저희가 원하는 컨셉과 기능을 빠르고 정확히 파악해주셨습니다. 덕분에 계획했던 일정보다 훨씬 빠르게 프로젝트가 마무리되었습니다. 품질과 속도 모두 만족스럽게 믿고 맡길 수 있는 개발사입니다. 추후 추가 기능 개발도 고민 중인데 당연히 다시 의뢰할 예정입니다." },
      { author: "(주) ***ECH", subtitle: "시리즈 A테크 스타트업", quote: "시리즈A 투자를 받은 테크 스타트업입니다. 처음에는 홈페이지 내부의 콘텐츠 디자인 작업만 맡기려 하였다가 개발까지 가능하다고 하여 기획 / 디자인 / 개발 턴키로 의뢰를 드렸는데 정말 믿고 맡길 수 있는 업체였습니다. 초안으로 넘겨주신 디자인은 회사 구성원들 모두가 이견이 없는 수준이었습니다. 저희 스타트업의 특성과 BI를 잘 반영하여서 홈페이지를 개발해주셨습니다." },
      { author: "***핏", subtitle: "고려대학교 크림슨창업지원단", quote: "소통과 속도, 그리고 실력까지 뭐 하나 빠지는 것이 없는 곳입니다! 프로젝트 일정이 정말 타이트했고, 개발이 끝난 이후에 요구사항이 몇 가지 있었는데 제로 스튜디오 허** PM님이 해외에 계신 상황에서도 요구 사항 반영을 위해 힘써주셔서 정말 감사했습니다." },
      { author: "덩****", subtitle: "", quote: "저희 서비스의 본질을 완벽히 이해하시고 작업을 하셨다는게 느껴졌습니다. 디자인적인 요소가 많이 필요했던 홈페이지라서 난이도가 높았을텐데 너무 잘 만들어주셨습니다. 소통도 잘 되고, 강추합니다!" },
      { author: "한원", subtitle: "", quote: "MVP 개발 과정을 단계별로 배울 수 있어서 실제 프로젝트에 바로 적용할 수 있었어요." },
      { author: "KUB******", subtitle: "", quote: "여러 업체들과의 미팅 중에 유일하게 가능하다고 하신 사막의 오아시스 같은 존재십니다. 프로젝트 진행에 있어, 비전공자라 커뮤니케이션에 어긋나는 부분에 대해선 비전공자도 이해하기 쉽게 설명을 해주셔서 너무 좋았고, 프로젝트 결과물에 대해 너무 만족합니다. MVP 진행하시려는 분들에게 강추 드립니다." },
      { author: "앉****", subtitle: "", quote: "작업 속도도 말씀 주신대로 준수해주시고 매우 친절한 상담과 함께 원하던 감각적인 디자인으로 이끌어 내 주셔서 대단히 감사합니다. 역시 이름에 걸맞게 크레임 제로인 스튜디오인 것 같네요." },
      { author: "정**", subtitle: "", quote: "작업 요청이 많은 프로젝트였지만, 일정 관리와 커뮤니케이션 모두 매끄러웠습니다. 디자이너와 개발자가 따로 놀지 않도록 설계부터 개발까지 일관된 구조로 작업해주신 점이 특히 만족스러웠습니다. 마무리 이후 유지 보수도 성실하게 대응해주셔서 내부에서도 반응이 좋습니다." },
      { author: "택**", subtitle: "", quote: "디자인부터 개발까지 전 과정을 원스톱으로 해주셔서 시간도 많이 아끼고, 퀄리티도 아주 만족스러웠어요. 중간중간 수정 요청에도 빠르게 대응해주시고, 어려운 용어는 쉽게 풀어서 설명해주셔서 저 같은 비전공자도 부담 없이 함께할 수 있었습니다." },
      { author: "B****", subtitle: "콘텐츠 커머스 스타트업", quote: "기획안이 막연한 상태에서 출발했는데, 요구사항을 빠르게 정리하고 우리가 생각지도 못한 UX 흐름까지 제안해주셔서 방향을 바로잡을 수 있었습니다. 일정이 촉박한 상황에서도 개발과 QA까지 꼼꼼히 챙겨주셔서 무사히 런칭할 수 있었어요. 다음 프로젝트도 꼭 함께 하고 싶습니다." },
      { author: "***한", subtitle: "시드 투자 스타트업", quote: "서비스 고도화와 동시에 홈페이지 리뉴얼을 진행해야 했던 상황이었는데, 기획 방향을 정확히 이해하고 구조부터 콘텐츠 구성까지 우리 팀 내부처럼 고민해주셨습니다. 초기 기획 단계부터 정리된 제안서와 디자인, 개발 산출물까지 모든 과정이 체계적이라 안심하고 맡길 수 있었어요." },
      { author: "윤**", subtitle: "1인 쇼핑몰 창업자", quote: "홈페이지나 앱 만드는 게 이렇게 복잡한 일인지 몰랐는데, 하나하나 쉽게 설명해주시고 저희 입장에서 같이 고민해주셔서 너무 든든했어요. 디자인도 예쁘게 잘 나왔고, 특히 모바일로 봐도 깔끔해서 고객들 반응이 좋아요. 앞으로도 계속 함께 하고 싶은 파트너예요." },
      { author: "PI****", subtitle: "", quote: "처음엔 반신반의했는데 결과물을 받아보고 깜짝 놀랐어요. 디자인 감각도 좋고, 고객 입장에서 어떤 기능이 필요한지도 먼저 제안해주시더라고요. 수정 요청도 귀찮아하지 않으시고 세심하게 챙겨주셔서 정말 감사했어요." },
    ],
  },
  faq: {
    title: "05 FAQ",
    subtitle: "자주 묻는 질문들을 확인해보세요.",
    items: [
      { q: "어떤 서비스를 제공하나요?", a: "웹/앱 개발, 브랜딩, 마케팅 등 다양한 분야의 서비스를 제공합니다." },
      { q: "프로젝트 진행 절차는 어떻게 되나요?", a: "상담 → 기획 → 설계 → 개발 → 테스트 → 런칭 순으로 진행됩니다." },
      { q: "견적은 어떻게 받을 수 있나요?", a: "상담 신청을 통해 요구사항을 전달해 주시면 맞춤 견적을 안내해 드립니다." },
      { q: "프로젝트 기간은 얼마나 걸리나요?", a: "프로젝트 규모에 따라 상이하며, 상담 시 일정을 함께 조율합니다." },
      { q: "계약은 어떻게 진행되나요?", a: "견적 확정 후 계약서를 통해 정식 계약을 진행합니다." },
      { q: "유지보수도 가능한가요?", a: "네, 런칭 후 유지보수 및 운영 지원도 가능합니다." },
    ],
  },
  contact: {
    title: "06 Contact Us",
    subtitle: "궁금한 점이 있다면 언제든지 문의해주세요.",
    email: "contact@solidweb.kr",
    ctaTitle: "지금 바로 상담 신청하고 더 나은 비즈니스 환경을 경험하세요.",
    ctaButton: "상담 신청하기",
  },
  contactPage: {
    heroTitle: "결과를 만드는 웹, 함께 설계합니다.",
    heroSubtitle: "전략 기획부터 전환 설계, 성과 측정까지. 솔리드웹.",
    heroDesc: "의견을 남겨주시면 24시간 이내로 전문가가 연락드립니다.",
    submitLabel: "문의하기",
    sections: {
      visitPath: "1. 방문 경로",
      projectInfo: "2. 프로젝트 정보",
      contactInfo: "3. 인적사항",
    },
    placeholders: {
      projectName: "프로젝트 이름을 입력하세요.",
      projectDetail: "프로젝트 상세 설명을 입력하세요.",
      budget: "0",
      dateSelect: "날짜 선택",
      name: "성명",
      company: "회사명(선택)",
      phone: "연락처",
      position: "직책(선택)",
      email: "이메일",
    },
    labels: {
      budget: "예산 (-만원)",
      dueDate: "프로젝트 마감일",
      name: "성명",
      company: "회사명",
      phone: "연락처",
      position: "직책",
      email: "이메일",
      privacyConsent: "개인정보 수집 동의",
      privacyView: "보기",
    },
    validation: {
      visitPath: "방문 경로를 선택해주세요.",
      projectName: "프로젝트 이름을 입력해주세요.",
      projectType: "프로젝트 유형을 선택해주세요.",
      projectDetail: "프로젝트 상세를 입력해주세요.",
      budget: "예산을 입력해주세요.",
      budgetFormat: "숫자만 입력해주세요.",
      dueDate: "마감일을 선택해주세요.",
      name: "성명을 입력해주세요.",
      phone: "연락처를 입력해주세요.",
      phoneFormat: "연락처 형식을 확인해주세요.",
      email: "이메일을 입력해주세요.",
      emailFormat: "이메일 주소를 확인해주십시오.",
      privacy: "개인정보 수집에 동의해주세요.",
    },
  },
  footer: {
    addressLine1: "인천광역시 연수구 인천타워대로 323,",
    addressLine2: "에이동 8층 801호 AB-162 (송도동, 송도 센트로드)",
    representative: "채희승",
    businessNumber: "사업자등록번호: 603-13-80609",
    services: ["웹/앱 개발", "브랜딩", "마케팅"],
    privacy: "개인정보처리방침",
  },
  kakaoChatUrl: "https://pf.kakao.com/_xkxmzqX/chat",
  kakaoChannelUrl: "https://pf.kakao.com/_xkxmzqX",
} as const;
